- name: start apache service
  service: 
       name: httpd
       state: restarted
       enabled: yes
- name: start docker service
  service: 
       name: docker
       state: restarted
       enabled: yes
